---
title: "Other Census Bureau datasets in tidycensus"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, fig.width = 8)
```

The main intent of the tidycensus package is to return population characteristics of the United States in tidy format allowing for integration with simple feature geometries.  Its intent is not, and has never been, to wrap the universe of APIs and datasets available from the US Census Bureau. For datasets not included in tidycensus, I recommend Hannah Recht's excellent __censusapi__ package (https://github.com/hrecht/censusapi), which allows R users to access all Census APIs, and packages such as Jamaal Green's __lehdr__ package (https://github.com/jamgreen/lehdr) which grants R users access to Census Bureau LODES data.  

However, tidycensus does incorporate a select number of Census Bureau datasets outside the decennial Census and ACS that are aligned with the basic goals of the package.  One such dataset is the __Population Estimates API__, which includes information on a wide variety of population characteristics that is updated annually.  

Population estimates are available in tidycensus through the `get_estimates()` function.  Estimates are organized into __products__, which in tidycensus include `"population"`, `"components"`, `"housing"`, and `"characteristics"`.  The population and housing products contain population/density and housing unit estimates, respectively.  The components and characteristics products, in contrast, include a wider range of possible variables.  



